{
  "user_service": {
    "timestamp": 1746763799,
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_a', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa747bc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "phase": "fault",
    "host_cpu": "N/A",
    "net_rtt": "N/A",
    "host_memory": "N/A"
  },
  "order_service": {
    "timestamp": 1746763799,
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_b', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa747b760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "phase": "fault",
    "host_cpu": "N/A",
    "net_rtt": "N/A",
    "host_memory": "N/A"
  },
  "inventory_service": {
    "timestamp": 1746763799,
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_c', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa7469220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "phase": "fault",
    "host_cpu": "N/A",
    "net_rtt": "N/A",
    "host_memory": "N/A"
  },
  "notification_service": {
    "timestamp": 1746763799,
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_d', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa7526dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "phase": "fault",
    "host_cpu": "N/A",
    "net_rtt": "N/A",
    "host_memory": "N/A"
  }
}